# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4251fdcfd99ad30996e38a56914e4296fab234e82601629c49eccf15d5b710f2a28e1041844e21c1b1dfeca11555ddf317972c9444046a1f4c190fe676c550c6

test:
  secret_key_base: 7363faf832ddcb226536f740bead12a469de7dcb69bf58b9cdc7622bbeabb5e5b5eafc8c31393685cbfc84243c46fb20d0d45da7ccef946ef842b2c773cc5f29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
